-- Insert science-related questions
INSERT INTO `question` (`question`, `xp`, `category`) VALUES
('What is the chemical symbol for gold?', '40', 'Science'),
('Which planet is known as the Red Planet?', '30', 'Science'),
('What is the powerhouse of the cell?', '20', 'Science'),
('What is the speed of light in a vacuum?', '50', 'Science'),
('What is the largest organ in the human body?', '25', 'Science'),
('Which gas do plants absorb during photosynthesis?', '15', 'Science'),
('What is the Earth\'s primary source of energy?', '60', 'Science'),
('What is the smallest prime number?', '35', 'Science'),
('What is the formula for water?', '45', 'Science'),
('What element does "O" represent on the periodic table?', '20', 'Science'),

('Which country won the FIFA World Cup in 2018?', '40', 'Sports'),
('In which sport would you perform a slam dunk?', '30', 'Sports'),
('Who holds the record for the most Grand Slam tennis singles titles?', '20', 'Sports'),
('Which city hosted the 2016 Summer Olympics?', '50', 'Sports'),
('What is the most-watched annual sporting event in the world?', '25', 'Sports'),
('In golf, what is the term for a score of one stroke under par on a hole?', '15', 'Sports'),
('Which team has won the most Super Bowls in NFL history?', '60', 'Sports'),
('What is the diameter of a basketball hoop in inches?', '35', 'Sports'),
('Which country is famous for its dominance in the sport of cricket?', '45', 'Sports'),
('Who is the all-time leading scorer in NBA history?', '20', 'Sports'),

('Who painted "Starry Night"?', '40', 'Art'),
('Which artistic movement is known for its use of geometric shapes and primary colors?', '30', 'Art'),
('In which century did the Renaissance period begin?', '20', 'Art'),
('Who created the sculpture "The Thinker"?', '50', 'Art'),
('Which painting is often considered the "Mona Lisa of the North"?', '25', 'Art'),
('What is the technique of creating images by assembling small pieces of colored glass?', '15', 'Art'),
('Who is known for his "Campbell\'s Soup Cans" artwork?', '60', 'Art'),
('Which art form involves shaping figures or designs in three dimensions?', '35', 'Art'),
('Who painted the "Guernica" mural?', '45', 'Art'),
('What is the primary color used by the artist Mark Rothko in many of his paintings?', '20', 'Art'),

('What is the capital of Japan?', '40', 'Geography'),
('Which river is the longest in the world?', '30', 'Geography'),
('In which continent is the Sahara Desert located?', '20', 'Geography'),
('What is the highest mountain in the world?', '50', 'Geography'),
('Which country is known as the Land of the Rising Sun?', '25', 'Geography'),
('What is the capital city of Australia?', '15', 'Geography'),
('Which ocean is the largest by surface area?', '60', 'Geography'),
('In which country would you find the ancient city of Petra?', '35', 'Geography'),
('Which river flows through Cairo?', '45', 'Geography'),
('What is the capital of Canada?', '20', 'Geography'),

('Who was the first President of the United States?', '40', 'History'),
('In which year did Christopher Columbus first reach the Americas?', '30', 'History'),
('Who was the famous queen of ancient Egypt known for her beauty?', '20', 'History'),
('What event marked the start of World War II?', '50', 'History'),
('Which war was fought between the North and South regions of the United States?', '25', 'History'),
('Who was the leader of the Soviet Union during the Cuban Missile Crisis?', '15', 'History'),
('In which century did the Renaissance period take place?', '60', 'History'),
('What ancient city was known for the Hanging Gardens?', '35', 'History'),
('Who was the first emperor of China?', '45', 'History'),
('What is the Magna Carta?', '20', 'History');

-- Insert corresponding answers
INSERT INTO `answer` (`answer`, `correct`, `question_id`) VALUES
('Au', 1, 61),
('Ag', 0, 61),
('Fe', 0, 61),
('Hg', 0, 61),
('Mars', 1, 62),
('Venus', 0, 62),
('Jupiter', 0, 62),
('Saturn', 0, 62),
('Mitochondria', 1, 63),
('Nucleus', 0, 63),
('Ribosome', 0, 63),
('Endoplasmic Reticulum', 0, 63),
('299,792 kilometers per second', 1, 64),
('150,000 kilometers per second', 0, 64),
('200,000 kilometers per second', 0, 64),
('250,000 kilometers per second', 0, 64),
('Skin', 1, 65),
('Heart', 0, 65),
('Brain', 0, 65),
('Liver', 0, 65),
('Carbon dioxide', 1, 66),
('Oxygen', 0, 66),
('Nitrogen', 0, 66),
('Hydrogen', 0, 66),
('Sun', 1, 67),
('Wind', 0, 67),
('Coal', 0, 67),
('Water', 0, 67),
('2', 1, 68),
('3', 0, 68),
('1', 0, 68),
('0', 0, 68),
('H2O', 1, 69),
('CO2', 0, 69),
('O2', 0, 69),
('N2', 0, 69),
('Oxygen', 1, 70),
('Helium', 0, 70),
('Carbon', 0, 70),
('Nitrogen', 0, 70),

('France', 1, 71),
('Germany', 0, 71),
('Brazil', 0, 71),
('Spain', 0, 71),
('Basketball', 1, 72),
('Soccer (Football)', 0, 72),
('Tennis', 0, 72),
('Golf', 0, 72),
('Serena Williams', 1, 73),
('Roger Federer', 0, 73),
('Rafael Nadal', 0, 73),
('Novak Djokovic', 0, 73),
('Rio de Janeiro', 1, 74),
('Tokyo', 0, 74),
('London', 0, 74),
('Beijing', 0, 74),
('Super Bowl', 1, 75),
('FIFA World Cup Final', 0, 75),
('UEFA Champions League Final', 0, 75),
('Olympic Games Opening Ceremony', 0, 75),
('Birdie', 1, 76),
('Eagle', 0, 76),
('Par', 0, 76),
('Bogey', 0, 76),
('New England Patriots', 1, 77),
('San Francisco 49ers', 0, 77),
('Pittsburgh Steelers', 0, 77),
('Dallas Cowboys', 0, 77),
('18 inches', 1, 78),
('20 inches', 0, 78),
('22 inches', 0, 78),
('24 inches', 0, 78),
('India', 1, 79),
('Australia', 0, 79),
('England', 0, 79),
('South Africa', 0, 79),
('Kareem Abdul-Jabbar', 1, 80),
('LeBron James', 0, 80),
('Michael Jordan', 0, 80),
('Kobe Bryant', 0, 80),

('Vincent van Gogh', 1, 81),
('Pablo Picasso', 0, 81),
('Leonardo da Vinci', 0, 81),
('Claude Monet', 0, 81),
('Cubism', 1, 82),
('Impressionism', 0, 82),
('Surrealism', 0, 82),
('Abstract Expressionism', 0, 82),
('15th', 1, 83),
('16th', 0, 83),
('14th', 0, 83),
('17th', 0, 83),
('Auguste Rodin', 1, 84),
('Leonardo da Vinci', 0, 84),
('Pablo Picasso', 0, 84),
('Michelangelo', 0, 84),
('Girl with a Pearl Earring', 1, 85),
('The Scream', 0, 85),
('The Night Watch', 0, 85),
('The Birth of Venus', 0, 85),
('Mosaic', 1, 86),
('Collage', 0, 86),
('Sculpture', 0, 86),
('Pottery', 0, 86),
('Andy Warhol', 1, 87),
('Jackson Pollock', 0, 87),
('Salvador Dalí', 0, 87),
('Henri Matisse', 0, 87),
('Sculpture', 1, 88),
('Drawing', 0, 88),
('Painting', 0, 88),
('Photography', 0, 88),
('Pablo Picasso', 1, 89),
('Salvador Dalí', 0, 89),
('Vincent van Gogh', 0, 89),
('Leonardo da Vinci', 0, 89),
('Red', 1, 90),
('Blue', 0, 90),
('Yellow', 0, 90),
('Green', 0, 90),

('Tokyo', 1, 91),
('Beijing', 0, 91),
('Seoul', 0, 91),
('Bangkok', 0, 91),
('Nile', 1, 92),
('Amazon', 0, 92),
('Yangtze', 0, 92),
('Mississippi', 0, 92),
('Africa', 1, 93),
('Asia', 0, 93),
('South America', 0, 93),
('North America', 0, 93),
('Mount Everest', 1, 94),
('K2', 0, 94),
('Kangchenjunga', 0, 94),
('Lhotse', 0, 94),
('Japan', 1, 95),
('China', 0, 95),
('South Korea', 0, 95),
('Vietnam', 0, 95),
('Canberra', 1, 96),
('Sydney', 0, 96),
('Melbourne', 0, 96),
('Perth', 0, 96),
('Pacific Ocean', 1, 97),
('Atlantic Ocean', 0, 97),
('Indian Ocean', 0, 97),
('Southern Ocean', 0, 97),
('Jordan', 1, 98),
('Iraq', 0, 98),
('Iran', 0, 98),
('Saudi Arabia', 0, 98),
('Nile', 1, 99),
('Amazon', 0, 99),
('Yangtze', 0, 99),
('Mississippi', 0, 99),
('Ottawa', 1, 100),
('Toronto', 0, 100),
('Vancouver', 0, 100),
('Montreal', 0, 100),

('George Washington', 1, 101),
('Thomas Jefferson', 0, 101),
('John Adams', 0, 101),
('Abraham Lincoln', 0, 101),
('1492', 1, 102),
('1607', 0, 102),
('1776', 0, 102),
('1789', 0, 102),
('Cleopatra', 1, 103),
('Hatshepsut', 0, 103),
('Nefertiti', 0, 103),
('Alexander the Great', 0, 103),
('Invasion of Poland', 1, 104),
('Bombing of Pearl Harbor', 0, 104),
('D-Day Invasion', 0, 104),
('Treaty of Versailles', 0, 104),
('Civil War', 1, 105),
('Revolutionary War', 0, 105),
('World War I', 0, 105),
('Vietnam War', 0, 105),
('Nikita Khrushchev', 1, 106),
('Joseph Stalin', 0, 106),
('Vladimir Putin', 0, 106),
('Mikhail Gorbachev', 0, 106),
('15th', 1, 107),
('16th', 0, 107),
('14th', 0, 107),
('17th', 0, 107),
('Babylon', 1, 108),
('Athens', 0, 108),
('Rome', 0, 108),
('Carthage', 0, 108),
('Qin Shi Huang', 1, 109),
('Sun Tzu', 0, 109),
('Confucius', 0, 109),
('Mao Zedong', 0, 109),
('A historic document limiting the power of the monarch', 1, 110),
('A famous medieval battle', 0, 110),
('An ancient religious text', 0, 110),
('A constitutional monarchy', 0, 110);
